@baseUrl = http://localhost:8080

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "João da Silva",
  "dataNascimento": "1995-08-15",
  "sexo": "M",
  "telefone": "4833334444",
  "celular": "4899998888",
  "email": "joao@email.com",
  "obsevacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 202",
  "bairro": "Centro",
  "cidade": "Criciúma",
  "estado": "SC",
  "cep": "88802410"
}

### Listar alunos
GET {{baseUrl}}/alunos

### Listar alunos com paginacão
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Buscar aluno por ID
GET {{baseUrl}}/alunos/1

### Atualizar aluno
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
  "nome": "João da Silva Atualizado",
  "dataNascimento": "1995-08-15",
  "sexo": "M",
  "telefone": "4833334444",
  "celular": "4899998888",
  "email": "joao@email.com",
  "obsevacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 202",
  "bairro": "Centro",
  "cidade": "Criciúma",
  "estado": "SC",
  "cep": "88802-410"
}

### Excluir aluno
DELETE {{baseUrl}}/alunos/1

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "Vanessa Oliveira",
  "dataNascimento": "1998-03-22",
  "sexo": "F",
  "telefone": "4833334444",
  "celular": "4899998888",
  "email": "vanessa@email.com",
  "obsevacao": "Aluna já possiu boa avaliacão física",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 202",
  "bairro": "Centro",
  "cidade": "Criciúma",
  "estado": "SC",
  "cep": "88802410"
}

### Cadastrar aluno invalido
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "",
  "dataNascimento": "1995-08-15",
  "sexo": "maculino",
  "email": "emailinvalido",
  "obsevacao": "Aluno iniciante",
  "estado": "Santa Catarina",
  "cep": "88802410"
}

### Listar todos
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Listar por nome
GET {{baseUrl}}/alunos?nome=Joao&page=0&size=10&sort=nome,asc

### Listar por cidade
GET {{baseUrl}}/alunos?cidade=Criciúma&page=0&size=10&sort=nome,asc

### Listar por estado
GET {{baseUrl}}/alunos?estado=SC&page=0&size=10&sort=nome,asc

### Listar por email
GET {{baseUrl}}/alunos?email=vanessa@email.com&page=0&size=10&sort=nome,asc


