@baseUrl = http://localhost:8080

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "João da Silva",
  "dataNascimento": "1995-08-15",
  "sexo": "M",
  "telefone": "4833334444",
  "celular": "4899998888",
  "email": "joao@email.com",
  "obsevacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 202",
  "bairro": "Centro",
  "cidade": "Criciúma",
  "estado": "SC",
  "cep": "88802410"
}

### Listar alunos
GET {{baseUrl}}/alunos

### Listar alunos com paginacão
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Buscar aluno por ID
GET {{baseUrl}}/alunos/1

### Atualizar aluno
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
  "nome": "João da Silva Atualizado",
  "dataNascimento": "1995-08-15",
  "sexo": "M",
  "telefone": "4833334444",
  "celular": "4899998888",
  "email": "joao@email.com",
  "obsevacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 202",
  "bairro": "Centro",
  "cidade": "Criciúma",
  "estado": "SC",
  "cep": "88802-410"
}

### Excluir aluno
DELETE {{baseUrl}}/alunos/1

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "Maria Oliveira",
  "dataNascimento": "1998-03-22",
  "sexo": "M",
  "telefone": "4833334444",
  "celular": "4899998888",
  "email": "joao@email.com",
  "obsevacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 202",
  "bairro": "Centro",
  "cidade": "Criciúma",
  "estado": "SC",
  "cep": "88802410"
}